version: '3.5'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/root/redis
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379