version: "3.5"

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./volumes/redis:/root/redis
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo-entrypoint:/docker-entrypoint-initdb.d:ro
      - ./volumes/mongodb:/data/db
      - ./volumes/mongoconfig:/data/configdb
