[tool.poetry]
name = "blinders-pytransport-core"
version = "0.1.0"
description = ""
authors = ["Dat Nguyen <minhdat15012002@gmail.com>"]
readme = "README.md"
packages = [{ include = "blinders" }]

[tool.poetry.scripts]
transport = "blinders.pytransport:main"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.34.88"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
