name: Go Lint CI
on:
    push:
        branches: [main, dev]
    pull_request:
jobs:
    resolve-modules:
        name: Resolve Go Modules
        runs-on: ubuntu-20.04
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Checkout Sources and Resolve Go Modules
              uses: actions/checkout@v2
            - id: set-matrix
              run: ./cmd/resolve_go_modules.sh
    lint:
        name: Go Lint
        needs: resolve-modules
        runs-on: ubuntu-20.04
        strategy:
            matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.21"
                  cache: false
            - uses: actions/checkout@v3
            - name: Lint by golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: "v1.54"
                  working-directory: ${{ matrix.workdir }}
                  only-new-issues: true
