name: golangci-lint
on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    resolve-modules:
        name: Resolve Modules
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Checkout Sources
              uses: actions/checkout@v2
            - id: set-matrix
              run: ./cmd/resolve_go_modules.sh
    golangci:
        name: lint
        runs-on: ubuntu-latest
        strategy:
            matrix: ${{ needs.resolve-modules.outputs.matrix }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.21.3"
                  cache: false
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.54
                  working-directory: ${{ matrix.workdir }}
