name: Python CI
on:
  push:
    branches: [main, dev]
  pull_request:
jobs:
  main:
    name: Lint and Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"

      - name: Checking python
        run: python --version

      - name: Install development dependencies
        run: pip install poetry && poetry config virtualenvs.create false && poetry install --no-root

      - name: Install dependencies for submodules
        run: git ls-files --full-name -- "**/pyproject.toml" | xargs -n 1 dirname | xargs -I{} bash -c 'cd "{}" && poetry install'

      - name: Linting
        run: ./scripts/check_pylint.sh
